---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: get-ocp-version-run-empty-params
spec:
  params:
    - name: fbcFragment
      value: ""
  taskRef:
    resolver: "bundles"
    params:
      - name: bundle
        value: quay.io/hacbs-release/task-get-ocp-version:0.1
      - name: kind
        value: task
      - name: name
        value: get-ocp-version
